# Hypothesis_Testing_Assignment

## Q.1
 A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two units. A randomly selected sample of cutlets was collected from both units and measured? Analyze the data and draw inferences at 5% significance level. Please state the assumptions and tests that you carried out to check validity of the assumptions.

In [4]:
import numpy as np
import pandas as pd
df = pd.read_csv("Cutlets.csv")
df

    Unit A  Unit B
0   6.8090  6.7703
1   6.4376  7.5093
2   6.9157  6.7300
3   7.3012  6.7878
4   7.4488  7.1522
5   7.3871  6.8110
6   6.8755  7.2212
7   7.0621  6.6606
8   6.6840  7.2402
9   6.8236  7.0503
10  7.3930  6.8810
11  7.5169  7.4059
12  6.9246  6.7652
13  6.9256  6.0380
14  6.5797  7.1581
15  6.8394  7.0240
16  6.5970  6.6672
17  7.2705  7.4314
18  7.2828  7.3070
19  7.3495  6.7478
20  6.9438  6.8889
21  7.1560  7.4220
22  6.5341  6.5217
23  7.2854  7.1688
24  6.9952  6.7594
25  6.8568  6.9399
26  7.2163  7.0133
27  6.6801  6.9182
28  6.9431  6.3346
29  7.0852  7.5459
30  6.7794  7.0992
31  7.2783  7.1180
32  7.1561  6.6965
33  7.3943  6.5780
34  6.9405  7.3875

In [5]:
#    Two sample test
#    H0 = There is no difference in the average dia of the cutlet between two units.
#    H1 = There is a difference in the average dia of the cutlet between two units.

In [9]:
from scipy import stats
Zcal, P_value = stats.ttest_ind(df["Unit A"], df["Unit B"],equal_var=True)
Zcal, P_value

(0.7228688704678063, 0.4722394724599501)

In [11]:
print("Z statistic value:",Zcal)
print("P Value",P_value)

Z statistic value: 0.7228688704678063
P Value 0.4722394724599501

In [13]:
if P_value < 0.05:
    print("H0 is rejected and H1 is accepted")
else:
    print("H1 is rejected and H0 accepted")

H1 is rejected and H0 accepted

# Q.2
A hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) of reports of the laboratories on their preferred list. They collected a random sample and recorded TAT for reports of 4 laboratories. TAT is defined as sample collected to report dispatch.

# Analyze the data and determine whether there is any difference in average TAT among the different laboratories at 5% significance level.

In [15]:
import pandas as pd
import numpy as np
df1 = pd.read_csv("LabTAT.csv")
df1

     Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0          185.35        165.53        176.70        166.13
1          170.49        185.91        198.45        160.79
2          192.77        194.92        201.23        185.18
3          177.33        183.00        199.61        176.42
4          193.41        169.57        204.63        152.60
..            ...           ...           ...           ...
115        178.49        170.66        193.80        172.68
116        176.08        183.98        215.25        177.64
117        202.48        174.54        203.99        170.27
118        182.40        197.18        194.52        150.87
119        182.09        215.17        221.49        162.21

[120 rows x 4 columns]

In [17]:
''' Make it in single list with group '''
df1_single_data = pd.melt(df1, value_vars=["Laboratory 1","Laboratory 2","Laboratory 3","Laboratory 4"], var_name='Lab', value_name='TAT')
df1_single_data

              Lab     TAT
0    Laboratory 1  185.35
1    Laboratory 1  170.49
2    Laboratory 1  192.77
3    Laboratory 1  177.33
4    Laboratory 1  193.41
..            ...     ...
475  Laboratory 4  172.68
476  Laboratory 4  177.64
477  Laboratory 4  170.27
478  Laboratory 4  150.87
479  Laboratory 4  162.21

[480 rows x 2 columns]

In [19]:
#    Annova test
#    H0 = there is no difference in the average Turn Around Time (TAT) of reports of the laboratories
#    H1 = there is any difference in the average Turn Around Time (TAT) of reports of the laboratories

In [20]:
from statsmodels.formula.api import ols
anova1 = ols('TAT ~ C(Lab)',data=df1_single_data).fit()
anova1

In [21]:
import statsmodels.api as sm
table = sm.stats.anova_lm(anova1, type=1)
table

             df         sum_sq       mean_sq           F        PR(>F)
C(Lab)      3.0   79979.167089  26659.722363  118.704217  2.115671e-57
Residual  476.0  106904.608903    224.589515         NaN           NaN

In [22]:
pvalue =table['PR(>F)'][0]
pvalue.round(9)
alpha = 0.05

In [23]:
if pvalue < alpha:
    print("H0 is rejected and H1 is accepted")
else:
    print("H1 is rejected and H0 is accepted")

H0 is rejected and H1 is accepted

# Q.3.
 Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions.

In [27]:
import pandas as pd
df2 = pd.read_csv("BuyerRatio.csv")
df2

  Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [28]:
obs = np.array([[50, 142, 131, 70], [435, 1523, 1356, 750]])

In [29]:
X = stats.chi2_contingency(obs)

In [30]:
p_value = X[1]
p_value

0.6603094907091882

In [31]:
# Null hypothesis(H0) = all proportions are equal
# Alternate hypothesis(H1) = all proportions are not equal

In [32]:
if p_value < 0.05:
    print("Reject Null hypothesis, Accept Alternative hypothesis")
else:
    print("Accept Null hypothesis, Reject Alternative hypothesis")

Accept Null hypothesis, Reject Alternative hypothesis

## Q.4.
  TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain %  of the customer order forms. Any error in order form renders it defective and has to be reworked before processing.  The manager wants to check whether the defective %  varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences

In [34]:
import pandas as pd
df3 = pd.read_csv("Costomer+OrderForm.csv")
df3

    Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [35]:
# H0 = male-female buyer rations are similar across regions
# H1 = male-female buyer rations are not similar across regions

In [38]:
## calculating the critical value
import researchpy as rp

SyntaxError: ignored

In [41]:
table = pd.crosstab(df3["Phillippines"],[df3["Indonesia"],df3["Malta"],df3["India"]])
table

Indonesia     Defective                       Error Free
Malta         Defective Error Free             Defective Error Free
India        Error Free  Defective Error Free Error Free  Defective Error Free
Phillippines
Defective             0          0          2          4          2         21
Error Free            9          2         20         18         16        206

In [42]:
from scipy.stats import chi2_contingency

chi2, P_Value, dof, expected = chi2_contingency(table)
P_Value

0.6845505149379718

In [43]:
alpha = 0.05

In [44]:
if P_Value < alpha:
    print("H0 is rejected and H1 is accepted")
else:
    print("H1 is rejected and H0 is accepted")

H1 is rejected and H0 is accepted